name: serialtomo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - ipython
  - jupyterlab
  - matplotlib
  - ipympl
  - plotly=5.11.0
  - scikit-image
  - libgcc
  - gcc
  - tqdm
  - pip
  - stackview
